### ISSUE TITLE
How to find user for flickr

### ISSUE THREAD

**Issue by ManuCart** [beaufour/flickr-download#20]
Hi again
I have this error because I don't know how to find user name
Please help
```
Traceback (most recent call last):
  File "/usr/local/bin/flickr_download", line 11, in <module>
    load_entry_point('flickr-download==0.2.15', 'console_scripts', 'flickr_download')()
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 299, in main
    print_sets(args.list)
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 223, in print_sets
    user = Flickr.Person.findByUserName(username)
  File "/usr/local/lib/python2.7/dist-packages/flickr_api/reflection.py", line 288, in static_call
    r = method_call.call_api(method=flickr_method, **method_args)
  File "/usr/local/lib/python2.7/dist-packages/flickr_api/method_call.py", line 134, in call_api
    raise FlickrAPIError(resp["code"], resp["message"])
flickr_api.flickrerrors.FlickrAPIError: 1 : User not found```

**Comment by ManuCart** [comment]
May be found my error
Every photos on my account flickr are private.
Is a way to recovery privates photos?

**Comment by beaufour** [comment]
Yes, you can use the `-t` flag:
https://github.com/beaufour/flickr-download#user-authentication-support

It's a little wonky, but it works.

**Comment by ManuCart** [comment]
Hi, step by step dream come true.
Now I can list my sets but not retreive photo from a particular set because permission denied
What's wrong?
```
flickr_download -k <api key> -s <api secret> -t -d <set id>
Traceback (most recent call last):
  File "/usr/local/bin/flickr_download", line 11, in <module>
    load_entry_point('flickr-download==0.2.15', 'console_scripts', 'flickr_download')()
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 306, in main
    download_set(args.download, get_filename, args.quality)
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 97, in download_set
    download_list(pset, pset.title, get_filename, size_label)
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 128, in download_list
    os.mkdir(dirname)
OSError: [Errno 13] Permission denied: 'folder name'

**Comment by ManuCart** [comment]
Found my error it's "Permission denied" to create "folder name"
How save files in other location?

**Comment by beaufour** [comment]
@ManuCart The script uses the current directory always. So if you are having trouble creating a directory, try running the script from a directory you have write permissions to?

**Comment by ManuCart** [comment]
Ok, thanks for all
