### ISSUE TITLE
Auth Error on 2nd account

### ISSUE THREAD

**Issue by ManuCart** [beaufour/flickr-download#21]
Hi, I have working well on 1ft account and now I try to connect on 2nd account and I have this error
flickr_download -t -k <api_key> -s <secret_key>
```Traceback (most recent call last):
  File "/usr/local/bin/flickr_download", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 288, in main
    ret = _init(args.api_key, args.api_secret, args.user_auth)
  File "/usr/local/lib/python2.7/dist-packages/flickr_download/flick_download.py", line 50, in _init
    auth = Flickr.auth.AuthHandler()  # creates the AuthHandler object
  File "/usr/local/lib/python2.7/dist-packages/flickr_api/auth.py", line 89, in __init__
    resp = urllib2.urlopen(req.to_url())
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized```

**Comment by beaufour** [comment]
When you say account, do you mean it's another computer you are running this on, or do you mean you are trying to access another Flickr account?

**Comment by ManuCart** [comment]
It's another flickr account

**Comment by beaufour** [comment]
Since the error message is `Unauthorized` I wonder if maybe something went wrong with the authentication for your second account? Maybe try to re-auth?

**Comment by ManuCart** [comment]
Yes wrong account, sorry it's working again
