### ISSUE TITLE
Python 3 not supported

### ISSUE THREAD

**Issue by zdavatz** [beaufour/flickr-download#35]
I constantly get this error:
```
Traceback (most recent call last):
  File "/usr/bin/flickr_download", line 11, in <module>
    load_entry_point('flickr-download==0.2.19', 'console_scripts', 'flickr_download')()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2598, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2258, in load
    return self.resolve()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.4/site-packages/flickr_download/flick_download.py", line 195
    except IOError, ex:
                  ^
SyntaxError: invalid syntax
```

**Comment by beaufour** [comment]
Well the `/usr/lib64/python3.4` path makes me believe that you are not running Python 2.7.12 :) The exception syntax changed in Python 3, and the code doesn't run.

**Comment by zdavatz** [comment]
So your code only runs in 2.7?

**Comment by beaufour** [comment]
It doesn't work with Python 3, no.

**Comment by zdavatz** [comment]
Ok, it is working on Python 2.7. Thank you. 

Question: Is there some sort of progress bar? I would like to download about 100'000 Fotos from my account.

**Comment by beaufour** [comment]
There is no progress bar I'm afraid. You'll only see the list of photos as they are downloaded one by one.

**Comment by zdavatz** [comment]
Where will I see the list? In the console? At the moment I see no list.

**Comment by beaufour** [comment]
When you start downloading an album or something it'll list out each name it downloads one at a time in the console?

**Comment by beaufour** [comment]
Close because of inactivity
